name: "Manual Clean Up"

on:
 workflow_dispatch:
   inputs:
      environment:
        required: true
        type: string

   secrets:
      WORKSPACE_BASE:
        required: true
      AWS_ACCESS_KEY_ID:
        required: false
      AWS_SECRET_ACCESS_KEY:
        required: false
      TF_API_TOKEN:
        required: true
     
      
jobs:
 destroy-infrastructure:
   runs-on: ubuntu-latest
   if: github.ref == 'refs/heads/main'
   env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
   steps:
     - name: Checkout
       uses: actions/checkout@v3
     
     - name: Setup Terraform
       uses: hashicorp/setup-terraform@v2
       with:
         terraform_wrapper: true
         cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

     - name: Terraform Init
       id: init
       run: terraform init 
      
     - name: Show Destroy plan
       run: terraform plan -destroy -out destroy.tfplan -var-file='./configs/${{ inputs.environment }}.tfvars'
       continue-on-error: true

     - name: Display structure to include tfplan
       run: ls -R

     - name: Terraform destroy
       id: destroy
       run: terraform apply  "destroy.tfplan"
       